apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: rabbit
spec:
  type: LoadBalancer
  ports:
  - port: 32500
    targetPort: 15672
    nodePort: 32500
  selector:
    app: nginx